mode: daemonset
namespaceOverride: opentelemetry-collector
image:
  repository: otel/opentelemetry-collector-k8s
presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
config:
  receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  processors:
    batch:
  
  exporters:
    prometheus:
      # Prometheus will autodetect this collector
      endpoint: "0.0.0.0:8888"
      # This is just a prefix, nothing to do with k8s namespaces
      namespace: "otlp_stuff"
    otlp/jaeger:
      endpoint: "collector.linkerd-jaeger:14250"
  
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/jaeger]
