apiVersion: v1
kind: Service
metadata:
  name: apigw
  labels:
    app: apigw
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.endpoints.services.apigw.port }}
      targetPort: {{ .Values.endpoints.services.apigw.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: apigw
