apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-company
  template:
    metadata:
      labels:
        app: rest-company
    spec:
      containers:
        - name: rest-company
          image: {{ .Values.images.rest_company.repository }}:{{ .Values.images.rest_company.tag }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
