apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.endpoints.services.rest.company_service.name }}
  labels:
    app: rest-company
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.endpoints.services.rest.company_service.port }}
      targetPort: {{ .Values.endpoints.services.rest.company_service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: rest-company
