apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-company
  template:
    metadata:
      labels:
        app: rest-company
    spec:
      containers:
        - name: rest-company
          image: {{ .Values.images.rest_company.repository }}:{{ .Values.images.rest_company.tag }}
          env:
             - name: OTEL_EXPORTER_OTLP_ENDPOINT
               value: "{{ .Values.endpoints.services.infrastructure.opentelemetry_http_connector_endpoint }}"
             - name: TCP_PORT
               value: "{{ .Values.endpoints.services.rest.company_service.targetPort }}"
          ports:
            - name: http
              containerPort: {{ .Values.endpoints.services.rest.company_service.targetPort }}
              protocol: TCP
