apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Without this, it routes requests directly to the service target pods rather than the service itself. That is not what we want if we use Linkerd
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apigw
            port:
              number: {{ .Values.endpoints.services.apigw.port }}
