apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-user
  template:
    metadata:
      labels:
        app: grpc-user
    spec:
      containers:
        - name: grpc-user
          image: {{ .Values.images.grpc_user.repository }}:{{ .Values.images.grpc_user.tag }}
          env:
             - name: GRPC_OTEL_EXPORTER_OTLP_ENDPOINT
               value: "{{ .Values.endpoints.services.infrastructure.opentelemetry_grpc_connector_endpoint }}"
             - name: TCP_PORT
               value: "{{ .Values.endpoints.services.grpc.user_service.targetPort }}"
          ports:
            - name: http
              containerPort: {{ .Values.endpoints.services.grpc.user_service.targetPort }}
              protocol: TCP
