apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.endpoints.services.grpc.user_service.name }}
  labels:
    app: grpc-user
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.endpoints.services.grpc.user_service.port }}
      targetPort: {{ .Values.endpoints.services.grpc.user_service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: grpc-user
