apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-user
  template:
    metadata:
      labels:
        app: grpc-user
    spec:
      containers:
        - name: grpc-user
          image: fcracker79/k8s-experiment-user:{{ .Values.images.grpc_user.version }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
