apiVersion: skaffold/v4beta10
kind: Config
build:
    artifacts:
        - image: registry.hub.docker.com/fcracker79/k8s-experiment-company
          context: ../docker/rest/company  
          sync:
              infer:
                  - '**/*'
        - image: registry.hub.docker.com/fcracker79/k8s-experiment-user
          context: ../docker/grpc/user
          sync:
              infer:
                  - '**/*'
        - image: registry.hub.docker.com/fcracker79/k8s-experiment-apigw
          context: ../docker/apigw
          sync:
              infer:

deploy:
    helm:
        releases:
            - name: k8s-experiment
              chartPath: ../helm
              namespace: k8s-experiment
              # I had to create it separately as I needed to annotate it with
              # the Linkerd annotation
              createNamespace: false
              setValueTemplates:
                  images.rest_company.repository: "{{.IMAGE_REPO_registry_hub_docker_com_fcracker79_k8s_experiment_company}}"
                  images.rest_company.tag: "{{.IMAGE_TAG_registry_hub_docker_com_fcracker79_k8s_experiment_company}}@{{.IMAGE_DIGEST_registry_hub_docker_com_fcracker79_k8s_experiment_company}}"
                  images.grpc_user.repository: "{{.IMAGE_REPO_registry_hub_docker_com_fcracker79_k8s_experiment_user}}"
                  images.grpc_user.tag: "{{.IMAGE_TAG_registry_hub_docker_com_fcracker79_k8s_experiment_user}}@{{.IMAGE_DIGEST_registry_hub_docker_com_fcracker79_k8s_experiment_user}}"
                  images.apigw.repository: "{{.IMAGE_REPO_registry_hub_docker_com_fcracker79_k8s_experiment_apigw}}"
                  images.apigw.tag: "{{.IMAGE_TAG_registry_hub_docker_com_fcracker79_k8s_experiment_apigw}}@{{.IMAGE_DIGEST_registry_hub_docker_com_fcracker79_k8s_experiment_apigw}}"
            - name: nats
              repo: https://nats-io.github.io/k8s/helm/charts/
              remoteChart: nats
              version: 1.1.12
              namespace: nats
              createNamespace: true

